<a href="https://colab.research.google.com/github/PhanTheMinhChau/baitap/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **khai báo thư viện**

In [6]:
import numpy

## **khởi tạo vector/ma trận**

In [8]:
a = numpy.array([[1, 6,7],[87,5,9],[7,9,0]])
b = numpy.array([[2,6,7],[8,23,6],[-3,7,12]])

## **các phép toán:**


ma trận chuyển vị:

In [9]:
t_a = numpy.transpose(a)
t_b = numpy.transpose(b)
print(t_a)
print(t_b)

[[ 1 87  7]
 [ 6  5  9]
 [ 7  9  0]]
[[ 2  8 -3]
 [ 6 23  7]
 [ 7  6 12]]


cộng trừ hai ma trận:

In [15]:
c = a + b
d = a - b
print(c,d)

[[ 3 12 14]
 [95 28 15]
 [ 4 16 12]] [[ -1   0   0]
 [ 79 -18   3]
 [ 10   2 -12]]


nhân hai ma trận:

In [10]:
tich = numpy.dot(a,b)
print(tich)

[[ 29 193 127]
 [187 700 747]
 [ 86 249 103]]


tính ma trận ngịch đảo:

In [ ]:
nd_a = numpy.linalg.inv(a)
nd_b = numpy.linalg.inv(b)
print(nd_a)
print(nd_b)

Tính hạng ma trận:

In [ ]:
 rank_a = numpy.linalg.matrix_rank(a)
 rank_b = numpy.linalg.matrix_rank(b)
 print(rank_a)
 print(rank_b)